# Generated by Django 2.1.7 on 2019-03-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placearticle',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
