# Generated by Django 2.1.7 on 2019-04-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20190428_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='altitude',
            field=models.IntegerField(default=0, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Долгота'),
        ),
    ]
